name: Deploy to Cloudflare Pages
on:
    schedule:
        # Run every 24 hours
        - cron: "0 0 * * *"
    push:
    workflow_dispatch:

jobs:
    deploy:
        name: Deploy
        runs-on: ubuntu-latest
        
        strategy:
            matrix:
                repo: [TurboWarp/scratch-gui, scratchfoundation/scratch-gui]
                
        steps:
            - uses: actions/checkout@v2

            - name: Checkout scratch-gui
              uses: actions/checkout@v2
              with:
                  # We are tracking TurboWarp/scratch-gui instead of scratch-foundation/scratch-gui
                  repository: ${{ matrix.repo }}
                  path: scratch-gui
                  fetch-depth: 1
            
            - name: Setup Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: ${{ matrix.repo == 'TurboWarp/scratch-gui' && '14.x' || '16.x' }}
                  cache: 'npm'
                  cache-dependency-path: scratch-gui/package-lock.json
            
            
            - name: Declare some variables
              run: echo "sha=$(cd scratch-gui; git rev-parse HEAD)" >> "$GITHUB_ENV"
            
            - name: Install dependencies
              run: cd scratch-gui && npm install

            - name: Build project
              run: cd scratch-gui && npm run build
              env:
                # TW Compatibility
                ROOT: ${{ matrix.repo == 'TurboWarp/scratch-gui' && '/tw' || '' }}/${{ env.sha }}/
                NODE_ENV: production
                ROUTING_STYLE: wildcard

            - name: Deploy to gh-pages branch
              uses: JamesIves/github-pages-deploy-action@4.1.4
              with:
                branch: gh-pages
                folder: scratch-gui/build
                clean: false
                token: ${{ github.token }}
                repository-name: ${{ github.repository }}
                # if turbowarp then use /tw/ as the baseurl
                target-folder: ${{ matrix.repo == 'TurboWarp/scratch-gui' && 'tw/latest' || 'scratch/latest' }}
            
                
            - name: Deploy to hash root
              uses: JamesIves/github-pages-deploy-action@4.1.4
              with:
                branch: gh-pages
                folder: scratch-gui/build
                clean: false
                token: ${{ github.token }}
                repository-name: ${{ github.repository }}
                # if turbowarp then use /tw/ as the baseurl
                target-folder: ${{ matrix.repo == 'TurboWarp/scratch-gui' && 'tw' || 'scratch' }}/${{ env.sha }}